# Makefile 
# OSU CS 362 - Software Engineering II
# Group #3
# Final Project 

CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/

testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


# Final Project
unittestresults: unittest04.c unittest05.c unittest06.c unittest12.c dominion.o rngs.o
	echo "unittest04.c:" >> unittestresults.out
	gcc -o unittest04 -g unittest04.c dominion.o rngs.o $(CFLAGS)
	echo "unittest05.c:" >> unittestresults.out
	gcc -o unittest05 -g unittest05.c dominion.o rngs.o $(CFLAGS)
	echo "unittest06.c:" >> unittestresults.out
	gcc -o unittest06 -g unittest06.c dominion.o rngs.o $(CFLAGS)
	echo "unittest12.c:" >> unittestresults.out
	gcc -o unittest12 -g unittest12.c dominion.o rngs.o $(CFLAGS)

	./unittest04 >> unittestresults.out
	./unittest05 >> unittestresults.out
	./unittest06 >> unittestresults.out
	./unittest12 >> unittestresults.out

	gcov -c -b -f dominion.c >> unittestresults.out
	cat dominion.c.gcov >> unittestresults.out


unittest04: unittest04.c dominion.o rngs.o
	gcc -o unittest04 -g unittest04.c dominion.o rngs.o $(CFLAGS)

unittest05: unittest05.c dominion.o rngs.o
	gcc -o unittest05 -g unittest05.c dominion.o rngs.o $(CFLAGS)

unittest06: unittest06.c dominion.o rngs.o
	gcc -o unittest06 -g unittest06.c dominion.o rngs.o $(CFLAGS)

unittest12: unittest12.c dominion.o rngs.o
	gcc -o unittest12 -g unittest12.c dominion.o rngs.o $(CFLAGS)

player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player 

clean:
	rm -f *.o playdom.exe playdom player *.exe  *.gcov *.gcda *.gcno *.so *.out 
